### ISSUE TITLE
Buenas prácticas

### ISSUE THREAD

**Issue by jorgeatgu** [rafagarces/rafa-blot#6]
Unas cosicas que yo considero buenas prácticas.

Para mejor la legibilidad, cada clase o id que ocupe una línea
Como está ahora:
```CSS
nav::-webkit-scrollbar-track , main::-webkit-scrollbar-track {
        background: white ;
        }

```
Mejor:
```CSS
nav::-webkit-scrollbar-track, 
main::-webkit-scrollbar-track {
    background: white;
}
```

Comentarios mejor arriba no en el lateral. Y entre el valor y punto y coma no dejar espacio

Como esta ahora:
```CSS
html {
  font-size: 100% ;         /* 100% = 16px */
  }
```

Mejor:
```CSS
html {
    /* 100% = 16px */
    font-size: 100%;
}
```

Decimales:

En los font-size, pues bueno, pues bien, aceptamos barco... 
Pero en los padding margin, width, height ojito como lo interpretan los navegadores.
Ejemplo: https://jsfiddle.net/q5BQs/3/

Siempre, siempre es mejor usas clases que empezar a dar estilos a elementos HTML. En este caso puedes ir https://github.com/rafagarces/rafa-blot/blob/master/templates/copy-of-grid/entry.html

Y añadir al ```<main>``` una class, ejemplo: ```container-entries``` lo mismo con el parrafo y el link, te lo pongo todo en la sección mejor.

Como esta ahora: 
```CSS
main {
    grid-column-start: 2;
    grid-row: nav-start / nav-end;
    height: calc(100vh - 56px);
    overflow: auto;
    -webkit-overflow-scrolling: touch;
    padding: 3.247rem;
    box-sizing: border-box;
}

main p {
    font-size: 2.281em;
    line-height: normal;
    margin-bottom: 2.566rem;
    text-decoration: none;
    max-width: 80%;
}

main p a {
    text-decoration: underline;
    color: black;
}
```

Mejor:

```CSS
.container-entries {
    grid-column-start: 2;
    grid-row: nav-start / nav-end;
    height: calc(100vh - 56px);
    overflow: auto;
    -webkit-overflow-scrolling: touch;
    padding: 3.247rem;
    box-sizing: border-box;
}

.entries-paragraph {
    font-size: 2.281em;
    line-height: normal;
    margin-bottom: 2.566rem;
    text-decoration: none;
    max-width: 80%;
}

.entries-link {
    text-decoration: underline;
    color: black;
}
```

Si necesitas una review en vivo y en directo a través de la internet, podemos hacerla ;)

Un saludo

Lecturas recomendadas: https://github.com/bendc/frontend-guidelines https://cssguidelin.es/

**Comment by rafagarces** [comment]
Viendo como funcionan los contenidos dinámicos he tenido que aplicar los estilos utilizando las clases tal y como me comentas pero añadiéndoles un nivel más de especificidad (¿se dice así? xD)

Quedaría algo así:

```
.container-entries {
    grid-column-start: 2 ;
    grid-row: nav-start / nav-end ;
    height: calc(100vh - 56px) ;
    overflow: auto ;
    -webkit-overflow-scrolling: touch ;
    padding: 3.247rem;
    box-sizing: border-box ;
    }

    .entries-paragraph p {
      font-size: 2.281em ;
      line-height: normal ;
      margin-bottom: 2.566rem ;
      text-decoration: none ;
      max-width: 80% ;
      }

      .entries-link a {
        text-decoration: underline ;
        color: black ;
        }
 
```
¿Bien? Mal?

**Comment by jorgeatgu** [comment]
Entiendo que el blot este te genera elementos `p` y `a` , pero no tienes poder para poder meterle una clase ¿no? si la cosa es así, lo que has hecho esta bien. No entiendo porque tabulas tanto XD

Así es más legible ¿no?:

```CSS
.container-entries {
    grid-column-start: 2 ;
    grid-row: nav-start / nav-end ;
    height: calc(100vh - 56px) ;
    overflow: auto ;
    -webkit-overflow-scrolling: touch ;
    padding: 3.247rem;
    box-sizing: border-box ;
}

.entries-paragraph p {
    font-size: 2.281em ;
    line-height: normal ;
    margin-bottom: 2.566rem ;
    text-decoration: none ;
    max-width: 80% ;
}

.entries-link a {
    text-decoration: underline ;
    color: black ;
}
```

El espacio entre el punto y coma y el valor enciende todos mis TOC.

```    color: black; ```
