### ISSUE TITLE
Custom properties

### ISSUE THREAD

**Issue by jorgeatgu** [rafagarces/rafa-blot#8]
Las mal llamadas CSS variables.

Se declaran dentro de :root, en la parte superior del documento. Aunque más tarde las podrás reescribir. Eso lo verás en el ejemplo que te adjunto al final.

```CSS
:root {
  --nombre-de-tu-variables: #488cff;
  --secondary-color: #f4b4d4;
}
```

Y que podamos hacer con estas y con tu CSS, pues mira. Podemos declarar variables para tus tipos de letras.

Como lo tienes ahora:
```CSS
tipo-a {
  font-family: "TimesNewRoman", "Times New Roman", Times, Georgia, serif ;
  }

.tipo-b {
  font-family: Arial, Helvetica, sans-serif ;
  }
```

Después:

```CSS
:root {
   --times: "TimesNewRoman", "Times New Roman", Times, Georgia, serif;
   --arial: Arial, Helvetica, sans-serif;
}

.tipo-a {
    font-family: var(--times);
}

.tipo-b {
    font-family: var(--arial);
}
```

Modificar el valor de una custom properties en la cascada de CSS: https://developer.mozilla.org/en-US/docs/Web/CSS/--*

Que cosicas podemos hacer con estas custom properties a parte de generar y cambiarlas con CSS. Pues modificarlas con JavaScript 🚀

Ejemplo: https://a-clau.jorgeatgu.now.sh/charts/area/

Código: https://github.com/jorgeatgu/clau/blob/v2/src/js/color.js

En el ejemplo anterior cambio el color de la gráfica y del fondo, modifico las dos custom properties con JavaScript.

Aquí otro ejemplo: https://codepen.io/wesbos/full/adQjoY

Y que puedes hacer tu ahora, pues generar tu paleta de colores con custom properties de CSS. Los nombres como bien sabrás que sean lo suficientemente claros XD
